### ISSUE TITLE
Flash.flash.0.element est toujours null lors de test sur une méthode delete

### ISSUE THREAD

**Issue by Wenzav** [V-ed/Automne2017CakePHPProject#4]
https://github.com/V-ed/Automne2017CakePHPProject/blob/3a57fc5d2835553714684ea2d9383da27c3fd398/tests/TestCase/Controller/UsersControllerTest.php#L307

Mon Flash.flash.0.element (ou Flash.flash.0.message) est toujours null quand je fais un test sur le delete. Peut importe si c'est l'admin ou le user qui essaie. Selon mon coverage, le test arrête à $this->request->allowMethod(['post', 'delete']);

**Comment by V-ed** [comment]
Essai de mettre cette ligne au début de ton test :

`$this->enableRetainFlashMessages();`

Example :
```php
...
public function testingStuff(){
    $this->enableRetainFlashMessages();
    
    ...
    
}
...
```

Si cela ne fonctionne pas, tu pourra mettre ici ton test et les Fixtures associés à ton test et je regarderais ça!

**Comment by Wenzav** [comment]
Oui j'utilise cette ligne de code dans mes autres tests et tout fonctionne. Malheureusement, je ne crois pas que cela soit lié. Voici le retour de PHPUnit:

```cmd
PHPUnit 5.7.0 by Sebastian Bergmann and contributors.

.............F                                                    14 / 14 (100%)

Time: 8.41 seconds, Memory: 18.75MB

There was 1 failure:

1) App\Test\TestCase\Controller\UsersControllerTest::testDeleteAsAdmin
Session content for "Flash.flash.0.message" differs.
Failed asserting that null matches expected 'The user has been deleted.'.

C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\public_html_Unit_2\vendor\cakephp\cakephp\src\TestSuite\IntegrationTestCase.php:1049
C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\public_html_Unit_2\tests\TestCase\Controller\UsersControllerTest.php:421

FAILURES!
Tests: 14, Assertions: 39, Failures: 1.
```

Et voici le code que j'utilise:
```php
public function testDeleteAsAdmin()
    {
		$this->enableRetainFlashMessages();
		
	   $this->session([
            'Auth' => [
                'User' => [
                    'id' => 1,
					'username' => 'test',
					'password' => 'test',
					'first_name' => 'Bob',
					'name' => 'Bobby',
					'language' => 'English',
					'civility' => '-',
					'phone_number' => '514.514.5144',
					'email' => 'bob@bob.com',
					'adress' => '123 rue Bobby',
					'role' => 'Admin',
					'created' => '2017-09-27 00:43:43',
					'modified' => '2017-09-27 00:43:43'
                ]
            ]
        ]);
        
        $url = Router::url(['controller' => 'users', 'action' => 'delete', 666]);
        $this->post($url);
        
        $expected = "The user has been deleted.";
        $this->assertSession($expected, 'Flash.flash.0.message');
        $this->assertRedirect(['action' => 'index']);
    }
```

**Comment by Wenzav** [comment]
Flash.flash.0.message est null. La même chose se passe avec la méthode testDeleteAsUser. La couverture du code s'arrête à la ligne `$this->request->allowMethod(['post', 'delete']);` de ma fonction delete.

**Comment by V-ed** [comment]
Peux-tu envoyer la méthode de ton Controller qui contient la ligne `$this->request->allowMethod(['post', 'delete']);` que tu parle?

Cette méthode ne me dis rien... serait-ce du code qui serait dans la méthode `beforeFilter(Event $event)`?

**Comment by Wenzav** [comment]
C'est la première ligne de la méthode delete()

```php
public function delete($id = null)
{
    $this->request->allowMethod(['post', 'delete']);
    $user = $this->Users->get($id);
    if ($this->Users->delete($user)) {
        $this->Flash->success(__('The user has been deleted.'));
    } else {
        $this->Flash->error(__('The user could not be deleted. Please, try again.'));
    }
    $this->Auth->logout();
    return $this->redirect(['action' => 'index']);
}
```

**Comment by Wenzav** [comment]
public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $user = $this->Users->get($id);
        if ($this->Users->delete($user)) {
            $this->Flash->success(__('The user has been deleted.'));
        } else {
            $this->Flash->error(__('The user could not be deleted. Please, try again.'));
        }
	$this->Auth->logout();
        return $this->redirect(['action' => 'index']);
    }

Repost pour un peu plus de clartée

**Comment by V-ed** [comment]
En effet, si ça arrête à la ligne `$this->request->allowMethod(['post', 'delete']);`, le message Flash n'apparaîtra pas et ton test ne fonctionnera pas non plus.

Alright, je te conseille donc de faire un allow dans ton `beforeFilter` à la place de ton `$this->request->allowMethod(['post', 'delete']);`.

Example :
```php
public function beforeFilter(Event $event) {
    $this->Auth->allow(['index', 'view', 'home', 'useritems', 'boughtitems', 'bid']);
}
```

Ceci va allouer **seulement** les méthodes retrouvées dans l'array. Cela veux dire que toutes les autres méthodes devronts passer par la méthode `isAuthorized($user)`.

https://github.com/V-ed/Automne2017CakePHPProject/blob/3a57fc5d2835553714684ea2d9383da27c3fd398/src/Controller/AppController.php#L86-L97
Comme tu peux le voir dans les lignes ci-haut, dans mon `AppController.php`, tous les admins sont authorisés, même dans les méthodes bloquées par le `beforeFilter()`.

Ça, ça serait dans ton `AppController.php`, la base de tes Controller, donc tu peux Override ces méthodes dans tes autres controlleurs!

Example :
https://github.com/V-ed/Automne2017CakePHPProject/blob/3a57fc5d2835553714684ea2d9383da27c3fd398/src/Controller/UsersController.php#L155-L173
Ici, je override le `isAuthorized()` pour faire de la logique :
```
SI requete est edit / delete ALORS
    SI l'utilisateur connecté est celui où l'on veut edit / delete ALORS
        return TRUE // donc authorise l'utilisateur
    FIN SI
FIN SI

return authorisation par défaut // (tout les admins peuvent)
```

**Comment by V-ed** [comment]
Je te conseille de faire ça puisque comme ça, tu utilisera les conventions de CakePHP et ainsi, les tests devraient être plus sûr de mieux réussir (CakePHP se base ***beaucoup*** sur les conventions, et donc PHPUnit aussi!)

Si ça sa marche pas non plus, we'll need to go deeper... 👓

**Comment by V-ed** [comment]
Hmm, j'ai regardé dans mes projets et j'ai cette ligne moi aussi, j'imagine qu'elle sert à n'accepter que les requêtes `post` et `delete`... C'est un peu étrange, et en plus la ligne fonctionne quand tu n'est pas dans les tests...

J'ai eu un problème une fois où comme toi mon programme fonctionnait sur le site mais pas dans les tests... Peux tu envoyer dans un commentaire le contenu complet de ton fichier `UserFixtures.php`? Si c'est la même erreur que j'ai eu, ça sera facile à régler...

**Comment by Wenzav** [comment]
Merci pour ton temps mec :)

Malheureusement, je vais devoir attendre avant de tester cela, mais c'est sûr que j'essaie!
